### ISSUE TITLE
Encrypted phones supported?

### ISSUE THREAD

**Issue by edwardhuerta** [vishnunaini/lineage-surnia-releases#15]
Sorry, Issue #14 went completely wrong (you can delete it).

I encrypted my phone in the Settings.

Now I boot into TWRP and I cannot see my /data partition, and it cannot be mounted. I get a "cannot find crypto footer".

Can I still use your img files to update my phone? Right now I am on your February build and I want to update my phone to your latest release.

I believe my phone is a XT1524.

Thanks in advance!

**Comment by vishnunaini** [comment]
Encrypted phones are fully supported.

Mounting /data is not required to update the phone. Phone updates only change stuff in /system.

Also, Your twrp appears to be old. Please update it to version 3.1.0 to get crypto support if you really want to use /data mount.

Use squid twrp 3.1.0 from here
 https://forum.xda-developers.com/moto-e-2015/development/twrp-squid-twrp-recovery-moto-e-lte-t3137649 
 http://forum.xda-developers.com/devdb/project/?id=10398#downloads

to get twrp that works with nougat updates.


To update
Just go to twrp and apply update through adb sideload or from an USB. No need to mount /data.

**Comment by edwardhuerta** [comment]
Ok great information. 

Last question : I have a build from February already on my phone installed and running, can I install your latest lineage-14.1-20170503-04-vishnunaini-surnia release on top of that directly? Or must it be an incremental update process?

**Comment by vishnunaini** [comment]
Direct update is okay.
