### ISSUE TITLE
Formatting SD card as Internal Problem

### ISSUE THREAD

**Issue by emoney15** [vishnunaini/lineage-surnia-releases#2]
Hi! Thanks for still supporting the moto e 2015!  Just to let you know on the latest lineage os when i had my sd card formatted to internal after every reboot the data was wiped for the apps on the sd card.  I dont know if anyone else is having these issues,  for now i just went back to formatting sd card as portable.  thanks again!

**Comment by vishnunaini** [comment]
I myself use the sdcard as internal storage but do not face this issue.

Please detail your exact model type and email me the logcat logs if possible.

see here if you want to know how to get the logcat logs https://forum.xda-developers.com/showthread.php?t=1726238

**Comment by emoney15** [comment]
I'm on xt1526 boost mobile...it doesn't really reset the data but I had nova launcher on sd card and I have to set my defaults for launcher every time I reboot..that's an example 😉

**Comment by vishnunaini** [comment]
Nova launcher if set as default launcher has to start the moment lock screen unlocks or else the android system considers the app as absent and cleanly wipes the secure storage associated with the app in the userdata area. 

Please remember that the sdcard is not initiated the moment the screen unlocks. Sdcard initialises slowly and sometimes ten's of seconds later.

This is a design problem with android and not a specific problem with this rom.

The nova launcher user data will only be preserved if it is not the default launcher if it is inistalled in sdcard. Move it to the real internal storage and you won't face this problem.

I am still surprised at one thing. How did you install Nova to sdcard? Nova explicitly sets the manifest that it does not support sdcard installation. You won't even have the chance to move it to sdcard.

**Comment by emoney15** [comment]
I can move it there easily when it's formatted to internal just going to settings-apps.....the default thing has me confused since I never had that problem with the cm builds...also does it with camera and any other app on sd with defaults set...anyway you're doing a great job and love the rom I can live with a few bugs

**Comment by vishnunaini** [comment]
Nova won't allow you to move to sdcard if it set as the default launcher.

Don't set the default if you want it's userdata to be preserved.

As I said, a design issue on how the sdcard component is initialised.

**Comment by vishnunaini** [comment]
this screenshot shows how it for me and how it should be
![nova](https://cloud.githubusercontent.com/assets/20936265/21994117/18c2e130-dc44-11e6-8e71-814ad9423108.png)

**Comment by emoney15** [comment]
![screenshot_20170116-131110](https://cloud.githubusercontent.com/assets/25038351/21998838/09e7b24c-dc05-11e6-969a-0c6a3789dbf5.png)

Thats what i got, im going to try to factory reset and delete everything, reformat the card and try again cause something is funky here.

**Comment by emoney15** [comment]
Also the reason I probably never had this issue before is because I usually delete Trebuchet launcher so no need to ask for defaults oops...sorry for wasting your time keep up the good work!
