### ISSUE TITLE
Occasional failure to initialise cellular data connection after wifi disconnects

### ISSUE THREAD

**Issue by xpaixx** [vishnunaini/lineage-surnia-releases#3]
After disconnecting from WiFi phone doesn't switch to mobile Internet. Also it switches between 3g/4g despite being set to use only 3g at will.

**Comment by emoney15** [comment]
So I'm not the only one? Lol yeah the switching from Wi-Fi to mobile is glitchy on mine also...xt1526

**Comment by vishnunaini** [comment]
I was able to reproduce this bug and I will investigate into this when I have time.

**Comment by vishnunaini** [comment]
I am well aware this bug also exists in upstream lineageos.

I am facing some issues while trying to hit this bug. It only shows up in some edge cases at certain special conditions I am unable to isolate. This problem does not exist during all switches but only shows up in some conditions even when using the same router.  I will have to wait till the edge case shows up again and then isolate it.

**Comment by vishnunaini** [comment]
I want to know something? Is this problem more prevalent in 3G UMTS/HSPA networks comapared to LTE networks? I was only testing in LTE where it occurs rarely. If it is more prevalent in 3G I will make efforts to get my hands on a 3G SIM for testing.

**Comment by emoney15** [comment]
Yah it seems to happen to me more when I switch from Wi-Fi to 3G

**Comment by emoney15** [comment]
Seems like this issue is improving for me after latest builds

**Comment by vishnunaini** [comment]
The latest builds after Jan 18 include an updated wifi driver and switching code. Please report back o the severity of the issue.

**Comment by emoney15** [comment]
I got the Jan. 20 build fresh/clean install on my Boost Mobile XT1526 Moto E LTE, and i cannot hold a data signal it keeps putting an x by the signal radio and i have to put in airplane mode and then turn airplane mode off then it works for a little then goes out again shortly after.

**Comment by vishnunaini** [comment]
I also see the same issues sometimes on an XT1521 but it is not as prevalent as you have stated. XT1521 and XT1526 are very different on the modem side. I tried to locate the issue and the problem appears to be related to the qti ril daemon. I am working on shim for the daemon to handle better switching. I will have to analyse the battery impact of the shim etc. When it is complete I will push it to the official lineage sources.

Actually stop using this build and go to official lineage builds once they are out. I may even stop supporting this build entirely. I will keep uploading my personal builds here but no guarantees anymore.

**Comment by vishnunaini** [comment]
Which build did the problem get worse in ? Is 20170115 much more stable than 20170120?

**Comment by emoney15** [comment]
I thought it got a lot worse on the latest build 20170120. I had 20170118 for 2 days and didnt seem to have quite the issues im having with the latest build.  Usually its when i go off of wifi and on the mobile network, on the latest build it seems like i dropped my mobile signal every 15 minutes at a location where it is usually stable. Thanks!

**Comment by vishnunaini** [comment]
There was only a single change between 18 and 20 . I enabled PIC on DEXPREOPT.

But the 18 build had some big cdma changes on surnia compared to 15. If something broke for CDMA it should have broken on 18. PIC for apk's is not even related to telephony anyway.

**Comment by emoney15** [comment]
Yeah I was only on 18 for two days at the most so maybe I got lucky or i was in a different location...I currently went back to official cm13 needed some stability in my life

**Comment by dmolteni** [comment]
Hi, any news about this bug?
I have a XT1524 with LineageOS 14.1-20170223-NIGHTLY-surnia and it happens very often (to not say always). I haven't install all updates but with the last one the situation is worst.

**Comment by vishnunaini** [comment]
This is a very widespread bug in 7.1.1 across all msm8916(snap 420) devices(not just motorola). There is no good understanding on why it is happening. Upstream developers are looking into it but I think it will be dependent on qualcomm updating the 7.1.1 tree for msm8916.

There is a workaround.

Go to developer settings and enable Cellular Data Always active. There will be some battery impact but minor.

**Comment by dmolteni** [comment]
Thanks, for the moment Ill try this workaround, waiting bug will solved.

**Comment by vishnunaini** [comment]
I fixed some of the problems related to this bug in the latest release. Switching is not perfect yet but has improved a lot.

**Comment by emoney15** [comment]
Maybe the switching has improved but my battery life is terrible, I keep dropping signal all the time, and I've never seen 4g yet in locations i usually get 4g, it says Sprint instead of boost mobile on my lock screen, I'm on  xt1526

**Comment by vishnunaini** [comment]
The points you mentioned are components that are handled by the baseband processor. Baseband is a secondary processor on your phone that is independent of your main processor and it runs it's own proprietary operating system. My ROM or any ROM do not manipulate the baseband processor in any way. The phone can only make small requests to the baseband processor but apart from that the baseband processor is independent.

The network band and connection selection is handled by the baseband is out of my hands. It looks like the network issues might be because of changes on your carrier side.

As far as your observations on battery life is concerned I will make some observations.

**Comment by emoney15** [comment]
Hello...I just want to say that I don't think your rom is my problem...I have boost mobile xt1526 and every 7.0 rom I use states Sprint as my carrier and signal goes in and out, as soon as I go back to 6.0 rom it states Boost mobile as my carrier and everything works great ..maybe this variant of Moto e just can't have 7.0?  Keep up the good work my friend....also can't seem to get lte ever on 7.0 but works fine on 6.0..thanks again
