### ISSUE TITLE
"Do not disturb" rules don't end automatically

### ISSUE THREAD

**Issue by eduardoeae** [vishnunaini/lineage-surnia-releases#5]
I've set up some rules, and even with the option to end with next alarm, the phone stays in Do not disturb mode.

**Comment by vishnunaini** [comment]
I will look into it

**Comment by vishnunaini** [comment]
I ran a full android compatibility test suite run and could not find any issues with do not disturb rules. The CTS does very comprehensive tests on Do not Disturb rules and the build passed the test without any issue.

So, If any issue exists I will need more information from you to identify this bug.

**Comment by eduardoeae** [comment]
I've disabled it since then. I'll update to latest, enable it and test it more thoroughly then. Thanks.

**Comment by eduardoeae** [comment]
Quick update: The problem is still there. Even setting do not disturb for just an hour it doesn't return to normal. Setting it for just a couple of minutes works fine (less than 10 minutes). And when a call gets disconnected (usually because of my crappy carrier) it gets stuck in do not disturb too, and I have to disable it manually. I'll try and do a clean flash when I have time.

**Comment by vishnunaini** [comment]
Fixed in the latest release
