### ISSUE TITLE
xt1521 VoLTE not working

### ISSUE THREAD

**Issue by psyfii** [vishnunaini/lineage-surnia-releases#6]
even though enhanced LTE mode is enabled, VoLTE does not work, how do i get through this?

**Comment by vishnunaini** [comment]
Does your carrier support it? If your carrier supports it, then please give details about your carrier to check if the apn's for your carrier are present.

Some carriers use non-standard VoLTE protocols that are not exactly the same as the one's defined the GSMA. The ROM currently does not support these non-standard protocols as I cannot test them. Please detail who is your carrier so that we can seee if this is the case.

**Comment by psyfii** [comment]
**RELIANCE Jio** is my carrier and it does support VoLTE. Iam using VoLTE on my moto z play with the same carrier , i did check the APN settings all ok,same as on ma moto z. What do you mean by non standard VoLTE protocols?

**Comment by vishnunaini** [comment]
Bro, even I am on Jio and it works for me. It works for me and doesn't for you that means there is an edge case that was only tripped on your device.

 I will need for you to send me your logcat logs to debug if a issue exists.

Go here to see how to take logcat logs https://forum.xda-developers.com/showthread.php?t=1726238

I will need the radio variant of the logs.

**Comment by vishnunaini** [comment]
Do this, It should work even without root.

Go to about phone. Click 7 times on the build number. Go back to settings and enable Developer options.

Go down and enable USB debugging. Connect to your PC.

Run "adb devices" . Approve the authentication message on your phone.If your device appears in the list then go ahead with the next step.

Run "adb shell logcat -b radio > log.txt" and send me the log.txt.

**Comment by vishnunaini** [comment]
Try to do a clean flash of my latest build or do a clean flash of the official lineageos build and report back.

**Comment by psyfii** [comment]
C:\Users\amresh>adb devices
List of devices attached
TA38500W0Q      device

C:\Users\amresh>adb shell logcat -b radio > log.txt

nothing else comes up after the last command

**Comment by vishnunaini** [comment]
go look in the log.txt file. If data is there send it to me.

**Comment by psyfii** [comment]
[log.txt](https://github.com/vishnunaini/lineage-surnia-releases/files/742995/log.txt)

**Comment by vishnunaini** [comment]
I have taken the file and will try to analyse it in the next few days when I have time.

**Comment by vishnunaini** [comment]
The logs say Volte is succesfully enabled.

`02-01 00:34:36.555  3082  3082 D ImsManager: updateVolteFeatureValue: available = true, enabled = true, nonTTY = true`

 If there was any problem it would have said false. Are you using the default dialer? If not try using the default dialer.If you flashed the stock variant of opengapps, you shouldn't do that as it replaces the aosp dialer with google dialer that might not support volte. If you have changed your dialer to google dialer or some other dialer, You need to change back to the lineage one with a clean flash. 

Next time use the nano version of opengapps and not any bigger version.

**Comment by psyfii** [comment]
thanks dude.. will it be ok for me to flash to the official rom, will  you be able to assist me in that (official rom)

**Comment by psyfii** [comment]
ive used the nano ver of GAPPS, i think the dialer has been replaced read in the log when installing gapps, is there anyway of jus downloading the google play store and and google play services?

**Comment by vishnunaini** [comment]
Yeah, My ROM and official ROM are very close and only differ in some security features that generally don't matter to most people.

I generally only want people to use this page for bug reports and not support cases. I cannot guarantee that I will be answering your support questions.

**Comment by vishnunaini** [comment]
Nano version just has only the basics like google play services and play store. That is why I recommended the nano version.

**Comment by vishnunaini** [comment]
Try Nano or Pico variants.

**Comment by vishnunaini** [comment]
I am closing this issue for now If a real bug exists you can open it back.

**Comment by psyfii** [comment]
so there  is no other explanation  ?? :(

**Comment by psyfii** [comment]
okk thanks

**Comment by psyfii** [comment]
one more think do i have to use arm or arm 64?

**Comment by vishnunaini** [comment]
There might be many explanations but I can't pinpoint something exactly. If VOLTE doesn't work on a standard build as the zip(as is provided without any third party stuff installed) then that will be a bug I can look into.

**Comment by vishnunaini** [comment]
Use arm

**Comment by psyfii** [comment]
ok, please do look into it and  help me out.. adios

**Comment by vishnunaini** [comment]
Do a clean flash that includes wiping system,userdata,data,internal storage.

**Comment by vishnunaini** [comment]
If you want help on how to deal with Custom ROMs there are support forums on https://forum.xda-developers.com and https://www.reddit.com/r/lineageOS where many passionate people will help you step by step.
